CREATE TABLE url (
  url_id SERIAL PRIMARY KEY,
  short_url TEXT NOT NULL UNIQUE,
  original_url TEXT NOT NULL,
  user_id VARCHAR(100) NOT NULL,
  public BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);