// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	UrlID       int32
	ShortUrl    string
	OriginalUrl string
	UserID      string
	Public      bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
